### ISSUE TITLE
Zeppelin notebook not working. Getting null pointer expression for sc.version

### ISSUE THREAD

**Issue by jegadesh33** [IBMDataScience/DSx-Desktop#44]
java.lang.NullPointerException
	at org.apache.zeppelin.spark.SparkInterpreter.open(SparkInterpreter.java:855)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:491)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:175)
	at org.apache.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:139)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sahilshah2211** [comment]
@jegadesh33 we are able to recreate this issue in our environment. We will be pushing out an update shortly to fix this issue.

**Comment by sahilshah2211** [comment]
@jegadesh33 The issue should be fixed in the 1.2.0 release. Please let us know if you still have problems.
