### ISSUE TITLE
json update 

### ISSUE THREAD

**Issue by jmuellerDO** [IBMDataScience/DSx-Desktop#47]
Hello DSX Community, 

since the last Windows 10 creators update i got [2017-11-27 12:36:19:0446] [error] Error while reading updates.json
[2017-11-27 12:36:19:0446] [error] "{ Error: self signed certificate in certificate chain\n at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)\n at emitNone (events.js:86:13)\n at TLSSocket.emit (events.js:185:7)\n at TLSSocket._finishInit (_tls_wrap.js:603:8)\n at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }"
and can't start DSX Desktop. 

Please help

Best regards
Joachim
[dsx-desktop.log](https://github.com/IBMDataScience/DSx-Desktop/files/1538992/dsx-desktop.log)

**Comment by jmuellerDO** [comment]
Hello DSX Community,

Changing the firewall to to not to use so restrictiv rules the Problem is solved.

Best regards
Joachim
