### ISSUE TITLE
Installation Failed - IBM Data Science Experience Desktop

### ISSUE THREAD

**Issue by Venkatesh6840** [IBMDataScience/DSx-Desktop#72]
**"Error: Object has been destroyed\n at EventEmitter.<anonymous> (C:\\Users\\IBM_ADMIN\\AppData\\Local\\ibm_dsx_desktop\\app-1.2.4\\resources\\app.asar\\webpack:\\app\\main.development.js:397:24)\n at Object.onceWrapper (events.js:316:30)\n at emitOne (events.js:115:13)\n at EventEmitter.emit (events.js:210:7)\n at WebContents.<anonymous> (C:\\Users\\IBM_ADMIN\\AppData\\Local\\ibm_dsx_desktop\\app-1.2.4\\resources\\electron.asar\\browser\\api\\web-contents.js:266:13)\n at emitTwo (events.js:125:13)\n at WebContents.emit (events.js:213:7)"

OS- Windows 7 Professional
System Type - 64 bit os

**Comment by Venkatesh6840** [comment]
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
--
Details: 00:00:00.802581 Power up failed (vrc=VERR_INTERNAL_ERROR, rc=E_FAIL (0X80004005))
[2018-06-29 14:01:09:0164] [error] stderr: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm ibm-dsx --type headless failed:
VBoxManage.exe: error: Nonexistent host networking interface, name 'VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTERNAL_ERROR)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
Details: 00:00:00.802581 Power up failed (vrc=VERR_INTERNAL_ERROR, rc=E_FAIL (0X80004005))
[2018-06-29 14:01:09:0165] [error] Had trouble starting ibm-dsx docker machine
[2018-06-29 14:01:09:0165] [info] Received cancel from render process
[2018-06-29 14:01:09:0166] [error] Exception in cancel-dl listener
[2018-06-29 14:01:09:0321] [error] "Error: Object has been destroyed\n at EventEmitter.<anonymous> (C:\\Users\\IBM_ADMIN\\AppData\\Local\\ibm_dsx_desktop\\app-1.2.4\\resources\\app.asar\\webpack:\\app\\main.development.js:397:24)\n at Object.onceWrapper (events.js:316:30)\n at emitOne (events.js:115:13)\n at EventEmitter.emit (events.js:210:7)\n at WebContents.

**Comment by jerry1100** [comment]
@Venkatesh6840 just following up, is this still an issue for you?

**Comment by alabsinatheer** [comment]
I have the same issue even after I installed both the latest versions of VirtualBox and Docker.
